### ISSUE TITLE
Implementing Telegram Based Scheduler

### ISSUE THREAD

**Issue by Aniketk561** [wrecker3000/Zoom-Meeting-Bot#1]
If anyone has some idea how to implement scheduler in the bot through telegram , kindly put your suggestions and help perfecting the bot.

For contacting me on telegram, message @remand57

**Comment by plal99** [comment]
For implementing in telegram, the process is actually simple. You need to make a telegram bot first.

**Comment by plal99** [comment]
-  Visit this website... [https://www.codementor.io/@garethdwyer/building-a-telegram-bot-using-python-part-1-goi5fncay](url)

This has all the info needed to make a bot in telegram. Then get your chat_id and token (these should not be shared.)

This is how your token and chat id should look like.

TELEGRAM_TOKEN = '3844597452:AAGJWg8sxXRc28t-IJsAxt8fORsm53r2VA'
TELEGRAM_CHAT_ID = '179099703'

These are all that is needed

- Since no other libraries are needed, you just need to send message using POST method using requests. I have implemented it in my project (please have a look - [https://github.com/plal99/Google-Meet-Bot](url)) in the sendTelegram function.

- Keep all tokens, chat_id, passwords in a .env files. Since it is really private, do not share them and insert into .gitignore file so that you wont accidently push it using git

**Comment by plal99** [comment]
You can also implement the WhatsApp feature, but the issue is that [Twilio](https://www.twilio.com/docs/whatsapp/api) is the only API that supports WhatsApp messaging, and they do not support long term messaging.

**Comment by wrecker3000** [comment]
SOLVED...added scheduler

**Comment by Aniketk561** [comment]
SOLVED...added scheduler
